# =================== 生产环境专用配置 ===================
spring:
  jmx:
    enabled: false  # 彻底关掉 JVM JMX 暴露（生产）
  # 生产环境数据库配置
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: username
      password: password

# 生产环境日志配置
logging:
  level:
    root: WARN
    com.cloud.baseai: INFO
    org.springframework.web: WARN
    org.springframework.scheduling: WARN  # 减少日志噪音
    org.springframework.security: WARN
  file:
    name: /var/log/baseai-cloud/application.log

# 生产环境特定配置
baseai:
  # 生产环境增加线程池大小
  async:
    core-pool-size: 4
    max-pool-size: 16
    queue-capacity: 1000

  # 生产环境启用更严格的安全策略
  security:
    jwt:
      use-rsa: true  # 生产环境强制使用RSA
      rsa-private-key: ${JWT_RSA_PRIVATE_KEY}
      rsa-public-key: ${JWT_RSA_PUBLIC_KEY}
      access-token-expiration: 1800000   # 30分钟
      refresh-token-expiration: 604800000 # 7天
      enable-blacklist: true
      enable-device-fingerprint: true
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:"https://app.baseai.com,https://admin.baseai.com"}
      allowed-methods: [GET,POST,PUT,DELETE,OPTIONS]
      allowed-headers: [Authorization,Content-Type,X-Requested-With,X-Device-Fingerprint]
      exposed-headers: [Location]
      allow-credentials: true
    password:
      enable-complexity-check: true
      enable-weak-password-check: true
      min-length: 10
      lockout-threshold: 5
      lockout-duration-minutes: 15
    auth:
      enable-captcha: true
      captcha-threshold: 2
      enable-two-factor-auth: true

  # 生产环境启用缓存预热
  cache:
    application:
      enable-cache-warming: true

  scheduling:
    enabled: true
    pool:
      # 生产环境使用更大的线程池以支持高并发
      size: 25
      allow-core-thread-timeout: true
      keep-alive-seconds: 300  # 5分钟
    thread:
      name-prefix: "Prod-Scheduler-"
    shutdown:
      wait-for-tasks-to-complete: true
      # 生产环境给更多时间完成任务
      await-termination-seconds: 300  # 5分钟

  # 生产环境启用完整的审计功能
  audit:
    elasticsearch:
      enabled: true
      enable-ilm: true
    integrity:
      enabled: true
    reporting:
      enabled: true

# 生产环境监控配置
management:
  server:
    port: 8081            # 管理端口与业务口分离
    address: 127.0.0.1    # 仅本机/内网监听，或改成内网IP
  endpoints:
    web:
      base-path: /actuator
      exposure:
        # 生产环境限制暴露的端点，仅只读端点
        include: health,metrics,info,prometheus

  endpoint:
    health:
      # 生产环境可能不希望暴露详细信息
      show-details: when-authorized
      roles: ACTUATOR
  prometheus:
    metrics:
      export:
        enabled: true