# =================== 生产环境专用配置 ===================
spring:
  config:
    activate:
      on-profile: prod

  # 生产环境数据库配置
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

# 生产环境日志配置
logging:
  level:
    root: WARN
    com.cloud.baseai: INFO
    org.springframework.web: WARN
    org.springframework.scheduling: WARN  # 减少日志噪音

# 生产环境特定配置
baseai:
  # 生产环境增加线程池大小
  async:
    core-pool-size: 4
    max-pool-size: 16
    queue-capacity: 1000

  # 生产环境启用更严格的安全策略
  security:
    password:
      min-length: 12
      require-uppercase: true
      require-lowercase: true
      require-numbers: true
      require-special-chars: true
      max-age-days: 60

  # 生产环境启用缓存预热
  cache:
    application:
      enable-cache-warming: true

  scheduling:
    enabled: true
    pool:
      # 生产环境使用更大的线程池以支持高并发
      size: 25
      allow-core-thread-timeout: true
      keep-alive-seconds: 300  # 5分钟
    thread:
      name-prefix: "Prod-Scheduler-"
    shutdown:
      wait-for-tasks-to-complete: true
      # 生产环境给更多时间完成任务
      await-termination-seconds: 300  # 5分钟

  # 生产环境启用完整的审计功能
  audit:
    elasticsearch:
      enabled: true
      enable-ilm: true
    integrity:
      enabled: true
    reporting:
      enabled: true

# 生产环境监控配置
management:
  endpoints:
    web:
      exposure:
        # 生产环境限制暴露的端点
        include: health,metrics,info
  endpoint:
    health:
      # 生产环境可能不希望暴露详细信息
      show-details: when-authorized