# =================== 测试环境专用配置 ===================
# 测试环境日志配置
logging:
  level:
    root: WARN
    com.cloud.baseai: INFO

# 测试环境特定配置
baseai:
  security:
    jwt:
      use-rsa: false
      secret: test-secret-key-for-testing-only
      access-token-expiration: 3600000  # 1小时
    auth:
      enable-multi-device: false
      max-devices-per-user: 1
  # 测试环境启用模拟服务
  llm:
    openai:
      enabled: false

  scheduling:
    enabled: true
    pool:
      size: 8
    thread:
      name-prefix: "Test-Scheduler-"
    shutdown:
      wait-for-tasks-to-complete: true
      await-termination-seconds: 30