# 测试环境配置
spring:
  config:
    activate:
      on-profile: test

baseai:
  chat:
    rate-limit-enabled: false
  llm:
    mock:
      enabled: true
      simulate-errors: true
      error-rate: 0.05

email:
  async: true
  retry:
    max-attempts: 5
  batch:
    size: 100

sms:
  async: true
  limit:
    per-minute: 10
    per-hour: 50
    per-day: 500

audit:
  async:
    enabled: true
  batch:
    size: 200
    timeout: 3000
  elasticsearch:
    enabled: true
  integrity:
    check:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: never
