# =================== 测试环境专用配置 ===================
spring:
  config:
    activate:
      on-profile: test

# 测试环境日志配置
logging:
  level:
    root: WARN
    com.cloud.baseai: INFO

# 测试环境特定配置
baseai:
  # 测试环境启用模拟服务
  llm:
    openai:
      enabled: false
    mock:
      enabled: true
      simulated-delay: PT0.5S
      simulate-errors: false
      error-rate: 0.1

  scheduling:
    enabled: true
    pool:
      size: 8
    thread:
      name-prefix: "Test-Scheduler-"
    shutdown:
      wait-for-tasks-to-complete: true
      await-termination-seconds: 30